FROM ubuntu

RUN echo uname -a = $(uname -a)
RUN echo uname -m = $(uname -m)

RUN echo dpkg --print-architecture = $(dpkg --print-architecture)
RUN echo dpkg --print-foreign-architectures = $(dpkg --print-foreign-architectures)
